# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish nuget
    env:
      NugetApiKey: ${{ secrets.NUGETAPIKEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
      - run: dotnet pack -o nuget
      - run: dotnet nuget push nuget/FlowTesterVersion1.1.0.0.nupkg --api-key $NugetApiKey --source https://api.nuget.org/v3/index.json