name: Release

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Building projects
        run: dotnet build --configuration Release --no-restore -o build
      - name: Running Tests
        run: dotnet test --verbosity normal

  release:
    name: 'Release to GitHub'
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      NugetApiKey: ${{ secrets.NUGETAPIKEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - name: Add plugin for executing bash commands
        run: npm install @semantic-release/exec -D
        working-directory: ./.github/workflows
      - name: Dry Run Semantic to get next Version nummber
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: 31892312+thygesteffensen@users.noreply.github.com
        run: |
          echo "RELEASE_VERSION=$(npx semantic-release --dry-run | grep 'Release note' | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+([-][a-zA-z]+[.][0-9]*)")" >> $GITHUB_ENV
      - name: print release verison
        run: echo $RELEASE_VERSION
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Package Parser
        run: dotnet pack -o artifacts -p:PackageVersion=$RELEASE_VERSION
        if: ${{ env.RELEASE_VERSION }}
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: thygesteffensen
          GIT_AUTHOR_EMAIL: 31892312+thygesteffensen@users.noreply.github.com
        run: npx semantic-release